stages:
  query_data:
    cmd: python scripts/real/query_data.py
    deps:
      - scripts/real/query_data.py
      - scripts/helpers/yaml_reading.py
    params:
      - configs/data_process_params.yaml:
          - kep_query_cols
          - eb_table_cols
    outs:
      - data/raw/Kepler_Confirmed_ExoPlanets.csv
      - data/raw/Kepler_Confirmed_EB.csv

  prepare_kepler_exo_data:
    cmd: python scripts/real/prepare_kepler_exo_data.py
    deps:
      - scripts/real/prepare_kepler_exo_data.py
      - data/raw/Kepler_Confirmed_ExoPlanets.csv
    params:
      - configs/data_process_params.yaml:
          - exo_input_file
          - exo_skipped_rows
          - exo_output_folder
    outs:
      - data/processed/exo_data

  prepare_kepler_eb_data:
    cmd: python scripts/real/prepare_kepler_eb_data.py
    deps:
      - scripts/real/prepare_kepler_eb_data.py
      - data/raw/Kepler_Confirmed_EB.csv
    params:
      - configs/data_process_params.yaml:
          - eb_input_file
          - eb_skipped_rows
          - eb_output_folder
    outs:
      - data/processed/eb_data

  organize_data:
    cmd: python scripts/real/organize_data.py
    deps:
      - scripts/real/organize_data.py
      - scripts/helpers/temp_help_name.py
      - scripts/helpers/yaml_reading.py
      - data/processed/exo_data
      - data/processed/eb_data
    params:
      - configs/data_process_params.yaml:
          - organize_train_ratio
          - organize_val_test_ratio
          - organize_seed
    outs:
      - data/real_model/train.npz
      - data/real_model/val.npz
      - data/real_model/test.npz

  train_real_cnn:
    cmd: python scripts/real/train_real_cnn.py
    deps:
      - scripts/real/train_real_cnn.py
      - data/real_model/train.npz
      - data/real_model/val.npz
    params:
      - configs/real_cnn_params.yaml:
          - cnn_layers
          - training_and_compiling
    outs:
      - models/real_model.keras
    plots:
      - results/training_history.json
    metrics:
      - results/real_metrics.json

  evaluate_real_cnn:
    cmd: python scripts/real/real_cnn_model_evaluation.py
    deps:
      - scripts/real/real_cnn_model_evaluation.py
      - models/real_model.keras
      - data/real_model/test.npz
      - results/training_history.json
    params:
      - configs/evaluation_params.yaml:
          - threshold
    outs:
      - results/plots/confusion_matrix.png
      - results/plots/training_accuracy_history.png
      - results/plots/training_loss_history.png
      - results/plots/confidence_histogram.png
      - results/plots/confidence_correct_vs_incorrect.png
      - results/misclassified_results/misclassified_lightcurves.npz
      - results/test_predictions.csv
    metrics:
      - results/evaluation.json

  misclassified_report:
    cmd: python scripts/real/misclassified_report.py
    deps:
      - scripts/real/misclassified_report.py
      - results/misclassified_results/misclassified_lightcurves.npz
    outs:
      - results/misclassified_results/misclassified_lightcurves.html
      - results/misclassified_results/false_positive_high_confidence.html
      - results/misclassified_results/false_negative_high_confidence.html

  analyze_misclassified:
    cmd: python scripts/real/analyze_misclassified.py
    deps:
      - scripts/real/analyze_misclassified.py
      - scripts/helpers/misclassified_helper.py
      - scripts/helpers/yaml_reading.py
      - results/misclassified_results/misclassified_lightcurves.npz
    params:
      - configs/evaluation_params.yaml:
          - plots_info
    outs:
      - results/misclassified_results/misclassified_plots
      - results/misclassified_results/fp_distribution_stats.json
      - results/misclassified_results/fn_distribution_stats.json

  analyze_prediction_groups:
    cmd: python scripts/real/analyze_prediction_groups.py
    deps:
      - scripts/real/analyze_prediction_groups.py
      - scripts/helpers/yaml_reading.py
      - results/test_predictions.csv
      - data/real_model/test.npz
      - data/raw/Kepler_Confirmed_ExoPlanets.csv
      - data/raw/Kepler_Confirmed_EB.csv
    params:
      - configs/evaluation_params.yaml:
          - confidence_bins
          - confidence_labels
          - snr_quantile_groups
          - snr_group_labels
    outs:
      - results/prediction_group_analysis

