stages:
  prepare_kepler_exo_data:
    cmd: python scripts/real/prepare_kepler_exo_data.py
    deps:
      - scripts/real/prepare_kepler_exo_data.py
      - data/raw/Kepler_Confirmed_ExoPlanets.csv
    params:
      - configs/data_process_params.yaml:
          - exo_input_file
          - exo_skipped_rows
          - exo_output_folder
    outs:
      - data/processed/exo_data

  prepare_kepler_eb_data:
    cmd: python scripts/real/prepare_kepler_eb_data.py
    deps:
      - scripts/real/prepare_kepler_eb_data.py
      - data/raw/Kepler_Confirmed_EB.csv
    params:
      - configs/data_process_params.yaml:
          - eb_input_file
          - eb_skipped_rows
          - eb_output_folder
    outs:
      - data/processed/eb_data

  organize_data:
    cmd: python scripts/real/organize_data.py
    deps:
      - scripts/real/organize_data.py
      - data/processed/exo_data
      - data/processed/eb_data
    params:
      - configs/data_process_params.yaml:
          - organize_train_ratio
          - organize_val_test_ratio
          - organize_seed
    outs:
      - data/real_model/train.npz
      - data/real_model/val.npz
      - data/real_model/test.npz

  train_real_cnn:
    cmd: python scripts/real/train_real_cnn.py
    deps:
      - scripts/real/train_real_cnn.py
      - data/real_model/train.npz
      - data/real_model/val.npz
      - data/real_model/test.npz
    params:
      - configs/real_cnn_params.yaml
    outs:
      - models/real_model.keras
    metrics:
      - results/real_metrics.json

  evaluate_real_cnn:
    cmd: python scripts/real/real_cnn_model_evaluation.py
    deps:
      - scripts/real/real_cnn_model_evaluation.py
      - models/real_model.keras
      - data/processed/test_data.csv
    outs:
      - results/real_conf_matrix.png
      - results/accuracy.png
      - results/loss.png
    metrics:
      - results/evaluation.json