threshold: 0.5

plots_info:
  - name: "KOI Model SNR"
    col: "koi_model_snr"
    log: True

  - name: "Calculated SNR"
    col: "calculated_SNR"
    log: True

  - name: "Orbital Period"
    col: "koi_period"
    log: True

  - name: "Absolute Transit Depth"
    col: "transit_depth_abs"
    log: True

eb_threshold_checks: [0.0005, 0.001, 0.003, 0.005, 0.0075, 0.01, 0.025, 0.05, 0.1]