threshold: 0.5

plots_info:
  - name: "KOI Model SNR"
    col: "koi_model_snr"
    log: True

  - name: "Calculated SNR"
    col: "calculated_SNR"
    log: True

  - name: "Orbital Period"
    col: "koi_period"
    log: True

  - name: "Absolute Transit Depth"
    col: "transit_depth_abs"
    log: True

eb_threshold_checks: [0.003, 0.005, 0.0075, 0.01, 0.015, 0.02, 0.05]