kep_query_cols: ["kepid", "koi_disposition", "koi_model_snr", "koi_depth", "koi_period"]
eb_table_cols: ["kepid", "koi_disposition", "koi_model_snr", "koi_depth", "koi_period"]

exo_input_file: "/Users/aaryanthusoo/Desktop/UCL/CNN_Exoplanets/data/raw/Kepler_Confirmed_ExoPlanets.csv"
exo_skipped_rows: 0
exo_output_folder: "/Users/aaryanthusoo/Desktop/UCL/CNN_Exoplanets/data/processed/exo_data"

eb_input_file: "/Users/aaryanthusoo/Desktop/UCL/CNN_Exoplanets/data/raw/Kepler_Confirmed_EB.csv"
eb_skipped_rows: 0
eb_output_folder: "/Users/aaryanthusoo/Desktop/UCL/CNN_Exoplanets/data/processed/eb_data"

organize_train_ratio: 0.75
organize_val_test_ratio: 0.05
organize_seed: 42

shallow_threshold: 0.99