threshold: 0.5

plots_info:
  - name: "KOI Model SNR"
    col: "koi_model_snr"
    log: True

  - name: "Calculated SNR"
    col: "calculated_SNR"
    log: True

  - name: Orbital Period
    col: "koi_period"
    log: True


confidence_bins: [0.5, 0.7, 0.85, 1.0]
confidence_labels: ["Low", "Medium", "High"]
snr_quantile_groups: 3
snr_group_labels: ["Low SNR", "Medium SNR", "High SNR"]
