training_and_compiling:
  epochs: 20
  batch_size: 64
  learning_rate: 5e-4
  weight_decay: 1e-4
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]

cnn_layers:
  - type: "conv1d"
    channels: 32
    kernel_size: 11
    padding: "same"

  - type: "batch_norm"

  - type: "activation"
    activation: "relu"

  - type: "max_pooling1d"
    pool_size: 2

  - type: "dropout"
    rate: 0.10

  - type: "conv1d"
    channels: 64
    kernel_size: 7
    padding: "same"

  - type: "batch_norm"

  - type: "activation"
    activation: "relu"

  - type: "max_pooling1d"
    pool_size: 2

  - type: "dropout"
    rate: 0.15

  - type: "conv1d"
    channels: 128
    kernel_size: 5
    padding: "same"

  - type: "batch_norm"

  - type: "activation"
    activation: "relu"

  - type: "max_pooling1d"
    pool_size: 2

  - type: "dropout"
    rate: 0.15

  - type: "conv1d"
    channels: 128
    kernel_size: 3
    padding: "same"

  - type: "batch_norm"

  - type: "activation"
    activation: "relu"

  - type: "global_avg_pooling1d"

  - type: "dense"
    units: 128
    activation: "relu"

  - type: "dropout"
    rate: 0.25

  - type: "dense"
    units: 64
    activation: "relu"

  - type: "dropout"
    rate: 0.20

  - type: "dense"
    units: 3
    activation: "softmax"